name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
         python-version: 3.7
        
      # Runs a single command using the runners shell
      - name: Run pip
        run: |
         pip3 install selenium
         sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt install -y ./google-chrome-stable_current_amd64.deb

      # Runs a set of commands using the runners shell
      - name: Run python script
        run: |
          python3.7 click-ssr.py
